/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f405xx.h"
#include "system_stm32f4xx.h"
#include "eeprom_spi.h"
#include "lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t read_val = 0;

int main(void) {


	SPI1_Init();
	LcdInit();

	// Write 0x55 to address 0x0010
	EEPROM_WriteByte(0x0010, 0x55);

	// Read back value
	read_val = EEPROM_ReadByte(0x0010);

	while (1) {
		// Set breakpoint here and check read_val in Live Expressions
		aprint(0x80, read_val);
	}
}

