/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f405xx.h"
#include "system_stm32f4xx.h"

#define MPU6050_ADDR       0x68  // AD0=GND => 0x68
#define MPU6050_REG_PWR    0x6B
#define MPU6050_REG_ACCEL  0x3B
#define MPU6050_REG_GYRO   0x43
#define MPU6050_REG_TEMP   0x41
#define I2C_TIMEOUT        10000

void I2C2_Init(void);
void I2C2_Start(void);
void I2C2_Stop(void);
void I2C2_Write(uint8_t data);
uint8_t I2C2_Read_Ack(void);
uint8_t I2C2_Read_Nack(void);
void I2C2_WriteReg(uint8_t devAddr, uint8_t reg, uint8_t data);
void I2C2_ReadMulti(uint8_t devAddr, uint8_t reg, uint8_t *buf, uint8_t len);

void MPU6050_Init(void);
void MPU6050_ReadRaw(int16_t *accel, int16_t *gyro, int16_t *temp);
int16_t accel[3], gyro[3], temp;
int main(void)
{


    I2C2_Init();
    MPU6050_Init();

    while (1)
    {
        MPU6050_ReadRaw(accel, gyro, &temp);

        // Place a breakpoint here to see live values
        // accel[0], accel[1], accel[2]
        // gyro[0],  gyro[1],  gyro[2]
        // temp
        for(volatile int i=0; i<100000; i++);  // Small delay
    }
}

/* ------------------- I2C2 Initialization ------------------- */
void I2C2_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;    // Enable GPIOB clock
    RCC->APB1ENR |= RCC_APB1ENR_I2C2EN;     // Enable I2C2 clock

    // PB10=SCL, PB11=SDA → AF4, OpenDrain, PullUp, HighSpeed
    GPIOB->MODER   &= ~((3 << (10*2)) | (3 << (11*2)));
    GPIOB->MODER   |=  (2 << (10*2)) | (2 << (11*2));   // AF mode
    GPIOB->OTYPER  |=  (1 << 10) | (1 << 11);           // Open-drain
    GPIOB->PUPDR   |=  (1 << (10*2)) | (1 << (11*2));   // Pull-up
    GPIOB->OSPEEDR |=  (3 << (10*2)) | (3 << (11*2));   // High speed
    GPIOB->AFR[1]  |=  (4 << ((10-8)*4)) | (4 << ((11-8)*4)); // AF4

    I2C2->CR1 = I2C_CR1_SWRST;       // Reset I2C
    I2C2->CR1 = 0;

    I2C2->CR2 = 42;                  // APB1=42MHz
    I2C2->CCR = 210;                 // 100kHz => CCR=42MHz/(2*100k)=210
    I2C2->TRISE = 43;                // TRISE = Freq + 1

    I2C2->CR1 |= I2C_CR1_PE;         // Enable I2C2
}

/* ------------------- I2C2 Low-Level Functions ------------------- */
void I2C2_Start(void)
{
    I2C2->CR1 |= I2C_CR1_START;
    while(!(I2C2->SR1 & I2C_SR1_SB));
}

void I2C2_Stop(void)
{
    I2C2->CR1 |= I2C_CR1_STOP;
}

void I2C2_Write(uint8_t data)
{
    while(!(I2C2->SR1 & I2C_SR1_TXE));
    I2C2->DR = data;
    while(!(I2C2->SR1 & I2C_SR1_BTF));
}

uint8_t I2C2_Read_Ack(void)
{
    I2C2->CR1 |= I2C_CR1_ACK;
    while(!(I2C2->SR1 & I2C_SR1_RXNE));
    return I2C2->DR;
}

uint8_t I2C2_Read_Nack(void)
{
    I2C2->CR1 &= ~I2C_CR1_ACK;
    while(!(I2C2->SR1 & I2C_SR1_RXNE));
    return I2C2->DR;
}

/* ------------------- I2C2 Read & Write ------------------- */
void I2C2_WriteReg(uint8_t devAddr, uint8_t reg, uint8_t data)
{
    I2C2_Start();
    I2C2->DR = devAddr << 1;
    while(!(I2C2->SR1 & I2C_SR1_ADDR));
    (void)I2C2->SR2;
    I2C2_Write(reg);
    I2C2_Write(data);
    I2C2_Stop();
}

void I2C2_ReadMulti(uint8_t devAddr, uint8_t reg, uint8_t *buf, uint8_t len)
{
    I2C2_Start();
    I2C2->DR = devAddr << 1;
    while(!(I2C2->SR1 & I2C_SR1_ADDR));
    (void)I2C2->SR2;
    I2C2_Write(reg);

    I2C2_Start();
    I2C2->DR = (devAddr << 1) | 1;
    while(!(I2C2->SR1 & I2C_SR1_ADDR));
    (void)I2C2->SR2;

    for(uint8_t i=0; i<len-1; i++)
        buf[i] = I2C2_Read_Ack();
    buf[len-1] = I2C2_Read_Nack();

    I2C2_Stop();
}

/* ------------------- MPU6050 Functions ------------------- */
void MPU6050_Init(void)
{
    // Wake up the sensor
    I2C2_WriteReg(MPU6050_ADDR, MPU6050_REG_PWR, 0x00);
}

void MPU6050_ReadRaw(int16_t *accel, int16_t *gyro, int16_t *temp)
{
    uint8_t buf[14];
    I2C2_ReadMulti(MPU6050_ADDR, MPU6050_REG_ACCEL, buf, 14);

    accel[0] = (buf[0] << 8) | buf[1];
    accel[1] = (buf[2] << 8) | buf[3];
    accel[2] = (buf[4] << 8) | buf[5];

    *temp    = (buf[6] << 8) | buf[7];

    gyro[0]  = (buf[8] << 8) | buf[9];
    gyro[1]  = (buf[10] << 8) | buf[11];
    gyro[2]  = (buf[12] << 8) | buf[13];
}
